// Exports contract ABIs from the Foundry build into @yieldline/shared.
// Run `forge build --root contracts` first.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "contracts", "out");
const target = join(root, "packages", "shared", "src", "generated", "abis.ts");

const contracts = {
  mockUsdcAbi: "MockUSDC",
  mockTbillAbi: "MockTBILL",
  complianceRegistryAbi: "ComplianceRegistry",
  mockOracleAbi: "MockRWAOracle",
  oracleAdapterAbi: "OracleAdapter",
  registryAbi: "RWARegistry",
  riskEngineAbi: "RWARiskEngine",
  liquidityVaultAbi: "USDCLiquidityVault",
  creditVaultAbi: "RWACreditVault",
};

let source = "// Generated by scripts/export-abis.mjs from the Foundry build. Do not edit.\n";
for (const [exportName, contract] of Object.entries(contracts)) {
  const artifact = JSON.parse(readFileSync(join(outDir, `${contract}.sol`, `${contract}.json`), "utf8"));
  source += `\nexport const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, source);
console.log(`Wrote ${Object.keys(contracts).length} ABIs to ${target}`);
