import type { ProtocolView } from "./use-protocol";

// The documented workshop scenario from 06_RISK_ENGINE.md, shown until a deployment exists.
export const demoView: ProtocolView = {
  mode: "demo",
  loading: false,
  connected: false,
  account: undefined,
  market: {
    asset: "MockTBILL",
    model: "Tokenized Treasury simulation",
    nav: "$1.05",
    priceType: "NAV",
    oracleStatus: "Fresh",
    oracleAge: "4 min",
    oracleTone: "healthy",
    baseLtv: "75.00%",
    liquidationLtv: "82.00%",
    liquidityFactor: "90.00%",
    settlementFactor: "95.00%",
    freshnessFactor: "100.00%",
    effectiveLtv: "64.13%",
    redemptionDelay: "24 h simulated",
    permissioned: "Yes — demo allowlist",
    borrowingEnabled: true,
    paused: false,
  },
  position: {
    collateral: "100,000.00 mTBILL",
    rawValue: "$105,000.00",
    effectiveValue: "$89,775.00",
    borrowCapacity: "$67,331.25",
    debt: "$50,000.00",
    availableBorrow: "$17,331.25",
    liquidationCapacity: "$73,615.50",
    healthFactor: "1.4723",
    status: "Healthy",
    stage: "ACTIVE",
    tone: "healthy",
  },
  pool: {
    totalSupplied: "$100,000.00",
    availableLiquidity: "$50,000.00",
    borrowed: "$50,000.00",
    utilization: "50.00%",
    borrowApr: "7.00% model",
    supplyApr: "3.50% model",
    badDebt: "$0.00",
  },
  wallet: {
    tbill: "100,000.00",
    usdc: "$0.00",
    shareValue: "$100,000.00",
    maxWithdraw: "$50,000.00",
    eligible: true,
  },
  raw: null,
  roles: {
    oracleUpdater: false,
    complianceAdmin: false,
    riskAdmin: false,
    protocolAdmin: false,
    liquidationOperator: false,
    minter: false,
  },
};
